### ISSUE TITLE
Adding has a decorator does not work

### ISSUE THREAD

**Issue by carlostxm** [Sambego/storybook-state#18]
Hi,

I'm trying to configure the addon as a decorator following the example in the readme but I get the following error:

![image](https://user-images.githubusercontent.com/11058795/52277777-ca082080-2955-11e9-83be-7be9deacce43.png)

It seems that the Decorator type is not compatible with addDecorator.

BR,
Carlos.

**Comment by hipstersmoothie** [comment]
I am seeing this too. The state decorator in general doesn't seem to work `store.get("foo")` doesn't seem to cause a rerender

**Comment by Sambego** [comment]
@carlostxm I'll look into this, PRs are also welcome!

@hipstersmoothie to get a value that updates on each render, pass it along as props. The `get()` method is only to be used to get the initial value and in event handlers. The docs could use a bit of polishing to make this clearer :)

Example:
```
const store = new Store({
  active: true
});

<State store={store}>
  {state => [
    <ElementOne active={state.active} />,
    <ElementTwo checked={state.active} />
  ]}
</State>;
```

**Comment by filiplindbladh** [comment]
Hi! Thank you for you awesome work with this project. I'm pretty new to Storybook but I have a Question about the above stated syntax. When I use it my story source and typescript prop types does not work. It seems that it thinks that I want to display the state component instead of the actual component I want to show. Is there any workaround for that? The code and how it looks:

```
storiesOf("Components/TextInput", module)
    .add("Default textinput", () => (
        <State store={store}>
            {state => {
                return (
                    <TextInput
                        id="TextInput-1"
                        name="TextInput-1"
                        inputType={Type.TEXT}
                        placeholder="Placeholder"
                        label="Label"
                        labelVisible={false}
                        value={state.inputone}
                        onChange={inputone => store.set({ inputone })}
                    />
                );
            }}
        </State>
    ));
```

<img width="1197" alt="Skärmavbild 2019-03-26 kl  10 53 33" src="https://user-images.githubusercontent.com/22678739/54988089-094a0980-4fb6-11e9-8a74-71595c9798d0.png">

**Comment by johansteffner** [comment]
I'm having the same issue using StateDecorator, this change to the definition seems to work:

```diff
 declare module '@sambego/storybook-state/StateDecorator' {
   /// <reference types="react" />
   import Store from '@sambego/storybook-state/Store';
   const StateDecorator: (
     store: Store<any>,
     parseState?: <S>(state: S) => S,
-  ) => (storyFn: any) => React.ReactNode;
+  ) => (storyFn: any) => React.ComponentType | JSX.Element;
   export default StateDecorator;
 }
```

**Comment by gh0stonio** [comment]
@Sambego hi and thx for your work, i'm trying to put the State component as a decorator in order to avoid seeing it in the story (in the info addon).
But by doing this i'm not able to have the store updated :/ do you have any idea how i can proceed to achieve that ?

Thanks a lot

**Comment by Sambego** [comment]
@gh0stonio thanks for trying out storybook-state!

Can you open a new issue, and post some code of what you're trying to do so I can take a look at it?

**Comment by hipstersmoothie** [comment]
@gh0stonio My coworker built a tiny storybook state utility to solve the problem your describing. it also works with addon-jsx pretty well. It a more hook like approach.

https://github.com/adierkens/storybook-addon-state
