### ISSUE TITLE
Error: Can't resolve 'proptypes'

### ISSUE THREAD

**Issue by krs-10** [Sambego/storybook-state#2]
Getting the following error: 

`./node_modules/@sambego/storybook-state/dist/State.js Module not found: Error: Can't resolve 'proptypes' in '/Users/<project path>/node_modules/@sambego/storybook-state/dist' @ ./node_modules/@sambego/storybook-state/dist/State.js 11:17-37 @ ./node_modules/@sambego/storybook-state/dist/index.js`

I submitted a pull request that fixes this issue: https://github.com/Sambego/storybook-state/pull/1

**Comment by Sambego** [comment]
Thanks for the pull request, I merged it, but will not be able to push a new release to npm until Monday.

**Comment by krs-10** [comment]
Awesome, thank you! I'll close this out :)

**Comment by Sambego** [comment]
Version `v1.0.4` has been published to npm.

**Comment by leonardofaria** [comment]
Sorry for reopening this.

I installed the version `1.0.4` and I still got the same `Can't resolve 'proptypes'` error.

I solved the issue by compiling the package again. Here is what I did: 
```
cd node_modules/@sambego/storybook-state
yarn install
yarn run compile
```

Not sure what is the problem: despite you merged the PR it seems that the code in `dist` didn't update it.

**Comment by Sambego** [comment]
Hey @leonardofaria I recompiled and created a new version (`v1.0.5`). The problem should be resolved now,

**Comment by leonardofaria** [comment]
It works like a charm.

Thanks for the fast answer. I appreciate it.
