### ISSUE TITLE
In Storybook 5; updates to store do not re-render component

### ISSUE THREAD

**Issue by alienfacepalm** [Sambego/storybook-state#21]
I upgraded to Storybook 5, now when I do a `store.set()` the component does not re-render, the store has the correct data, but it just has the original render of defaults. Maybe I'm missing something. I am trying to figure out a way to use Subscribe to get it re-render, with no luck yet.

**Comment by ZakRabe** [comment]
hey my team and I were trying were unable to solve this problem for a while as well. I figured it out today.

heres a story I wrote that basically replicates what react does on a setState

```import React from 'react';
import PhoneNumberInput from '../src/components/Inputs/PhoneNumberInput';
import { storiesOf, forceReRender } from '@storybook/react';
import { StateDecorator, Store } from '@sambego/storybook-state';
import { withInfo } from '@storybook/addon-info';

const stories = storiesOf('Components/Inputs/PhoneNumberInput', module);

const store = new Store({
  value: 7575551234,
});

store.subscribe((state) => {
  forceReRender();
});
/**
 * PhoneNumberInput Story
 */
stories.addDecorator(StateDecorator(store)).add(
  'Default',
  withInfo({
    inline: true,
    text: 'This component is used to render a USA phone number with dashes.',
  })(() => {
    return (
      <div style={{ padding: 20 }}>
        <PhoneNumberInput
          key="test"
          value={store.get('value')}
          onChange={(value) => {
            store.set({ value });
          }}
        />
      </div>
    );
  }),
);
```

**Comment by alienfacepalm** [comment]
Ah, ForceReRender good find. I've got a ton of other issues with bad typings since I'm using TS, I cannot use the StateDecorator, I have to figure out how to fix the typings. Good lookin' out with the solution man. 

BTW, Does <Store /> use context api? If it did, I don't see how it wouldn't re-render, I guess I'll dive into the source and see how it's built.

**Comment by alienfacepalm** [comment]
Oh quick note as well, in order for this to work the `forceReRender` must be outside of the `.add()` it's scope won't re-render from within the Story. 

Badass, now to get the StateDecorator working in TS!

**Comment by ZakRabe** [comment]
Glad it helped. I don't know of the implementation details of the decorator, apologies. 

We're using TS in the component code, but we don't use it for the stories just out of convenience.

**Comment by themese** [comment]
forceReRender() did the trick for me, but is this the way to do it or just a hack/temporaly fix?
I'm new to this library and from the docs I understand that changing the store state should trigger a render automatically without needing to use the forceReRender().
Am I correct or not?

Thanks!

**Comment by alienfacepalm** [comment]
I wound up just using React 16.8.4 hooks and moving the component out of the Story and just render it in the story, if that helps, it works fine.

**Comment by pauldariye** [comment]
@alienfacepalm, I've tried using hooks but still cannot get the story to re-render.

**Comment by alienfacepalm** [comment]
You must not be doing it really outside of the Story then. 

```const stories = storiesOf('Form', module)

const ChipListStory: FC<any> = props => {
  const [items, setItems] = useState(chips)
  return <ChipList items={items} setItems={setItems} legend="Tappable actions to search for" />
}

stories.add(
  '1.8 Chip list',
  () => {
    return <ChipListStory />
})

```

**Comment by pauldariye** [comment]
works. Thanks @alienfacepalm
