### ISSUE TITLE
StateDecorator no longer matches Reacts expected decorator definition

### ISSUE THREAD

**Issue by Swiftwork** [Sambego/storybook-state#28]
StateDecorator definition needs an update to resolve.

```typescript
Argument of type '(storyFn: any) => Element | ComponentClass<{}, any> | FunctionComponent<{}>' is not assignable to parameter of type 'DecoratorFunction<StoryFnReactReturnType>'.
```

**Comment by Sambego** [comment]
Thanks for reporting. The addon is now compatible with storybook's new format for addons and decorators. Please update this addon to `v2.0.0`.  The readme is updated with info on the new decorator.
