### ISSUE TITLE
Incompatible with Storybook 5.3

### ISSUE THREAD

**Issue by cascornelissen** [Sambego/storybook-state#30]
We're using this project in combination with Storybook 5.3 and addon-docs and are writing stories using MDX. The recent 5.3 release of Storybook broke the components using state in our documentation.

When using `console.log` within the render method of these components it looks like `state` doesn't equal the object defined when instantiating a `new Store()` but instead contains the entire Storybook state (see the screenshot at the end of this issue).

**Example component**
```mdx
import { StateDecorator, Store } from '@sambego/storybook-state';

// ...

const storeComponent = new Store({
    values: ['A']
});

<Story name="Component" decorators={[StateDecorator(storeComponent)]}>
    {(state) => {
        console.log('Checkbox state', state);
        return (
            <React.Fragment>
                {['A', 'B', 'C'].map((value) => {
                    return <Checkbox label={`Checkbox ${value}`} value={value} onChange={handleChangeComponent} checked={state.values.includes(value)} />;
                })}
            </React.Fragment>
        );
    }}
</Story>
```

**Error that's shown in Storybook UI**
```
Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
    at http://localhost:6060/main.1bdd52c5e10938b27082.hot-update.js:167:29
    at Array.map (<anonymous>)
    at component (http://localhost:6060/main.1bdd52c5e10938b27082.hot-update.js:162:145)
    at http://localhost:6060/vendors~main.b4f33689a61e53810336.bundle.js:16077:21
    at http://localhost:6060/vendors~main.b4f33689a61e53810336.bundle.js:17380:16
    at http://localhost:6060/vendors~main.b4f33689a61e53810336.bundle.js:4159:7
    at http://localhost:6060/vendors~main.b4f33689a61e53810336.bundle.js:16077:21
    at http://localhost:6060/vendors~main.b4f33689a61e53810336.bundle.js:17379:14
    at http://localhost:6060/vendors~main.b4f33689a61e53810336.bundle.js:17380:16
    at withSubscriptionTracking (http://localhost:6060/vendors~main.b4f33689a61e53810336.bundle.js:17408:16)
```

**Returned state**

![image](https://user-images.githubusercontent.com/1304939/72353309-24703c00-36e4-11ea-9b2a-97def41db87c.png)

**Comment by Sambego** [comment]
Thanks for reporting. The addon is now compatible with storybook's new format for addons and decorators. Please update this addon to `v2.0.0`.

**Comment by Sambego** [comment]
The readme is updated with info on the new decorator.

**Comment by cascornelissen** [comment]
Awesome, thanks for the quick fix and replies @Sambego, just updated everything again and all is working now. 🚀
