### ISSUE TITLE
State not available unless passed-in as props?

### ISSUE THREAD

**Issue by moarwick** [Sambego/storybook-state#8]
Nice! I'm running into an issue where I'm trying to demo multiple components side by side. If I understand correctly, currently the only way to access State by a component is to wrap it with `State` and expect it as `props`. Any way to just pass state into props directly? In other words, any way to make the following work?

```
const checked1 = 'dresses';
const checked2 = 'tops';

const store = new Store({
  [checked1]: false,
  [checked2]: false,
});

stories.add('CheckboxField', () => {
  return (
    <div>
      <CheckboxField
        checked={store.get(checked1)}
        onChange={e => store.set({[checked1]: e.target.checked})}
      />
      <CheckboxField
        checked={store.get(checked2)}
        onChange={e => store.set({[checked2]: e.target.checked})}
      />
    </div>
  );
});
```

**Comment by jclarkpatientping** [comment]
You would need to wrap the `<div>` with a `<State store={store}>` component, I think.

**Comment by Sambego** [comment]
Hey @moarwick, you could try to create 2 quick helper components which pass along the prop to your `CheckboxField` component.

```javascript
const store = new Store({
  checked1: false,
  checked2: false,
});

const Checkbox1 = ({ checked1 } ) => <CheckboxField
  checked={checked1}
  onChange={e => store.set({checked1: e.target.checked})}
/>

const Checkbox2 = ({ checked2 } ) => <CheckboxField
  checked={checked2}
  onChange={e => store.set({checked2: e.target.checked})}
/>

stories.add('CheckboxField', () => {
  return (
    <div>
      <Checkbox1 />
      <Checkbox2 /<
    </div>
  );
});
```

**Comment by miracle2k** [comment]
Have you considered allowing the child of `State` to be a function. We could then pass the state around as we want.

**Comment by Sambego** [comment]
Hey @miracle2k, could you elaborate on that a bit more?

Do you mean something like this:
```
<State store={store}>
  state => [
    <Checkbox value={state.checked1} />
    <Checkbox value={state.checked1} />
  ]
</State>
```

**Comment by Sambego** [comment]
I added the possibility to add a function returning children to the `<State />` component. It's available in `1.3.0`.

It works like this:
```javascript
const store = new Store({
  active: true
});

<State store={store}>
  {state => [
    <ElementOne active={state.active} />,
    <ElementTwo checked={state.active} />
  ]}
</State>;
```

**Comment by miracle2k** [comment]
Cool, that's what I meant. Thanks for adding it!

**Comment by miracle2k** [comment]
I just tried it; what I do not like is that it still tries to process the children, and *again* tries to pass in the state. For example:

```
<State>
{
     state => {
         return <div>
             <ElementOne active={state.active} />
         <div>
    }
}
</State>
```

This fails with:

`this.props.children(...).map is not a function` 

because the library expects the function to return an array of children.

I believe that this example:

```
const store = new Store({
  active: true,
  foo: 'bar'
});

<State store={store}>
  {state => [
    <ElementOne enabled={state.active} />,
    <div>
         {state.active} {state.foo}
     </div>
  ]}
</State>
```

will end up being rendered as:

```
<ElementOne enabled={state.active}  active={state.active} foo="bar' />,
<div  active={state.active} foo="bar'>
    Current value: {state.active} 
</div>
```

which defeats the purpose of the flexibility that the state function gives me.

**Comment by Sambego** [comment]
Hey @miracle2k, can you make a new issue, with a code example of how you would like the `<State />` component to behave? I'll see what I can do after you've created the issue :)
